### ISSUE TITLE
Export to png nothing happens

### ISSUE THREAD

**Issue by LeHoangDev** [vuerd/vuerd-vscode#101]
Visual Studio Code 1.49.0
ERD Editor 0.7.2

I would like to export my diagram as png. When I am trying to export it via the context menu nothing happens. It stucks for one second and then the context menu disappears. Same situation with export as JSON or SQL DDL.

**Comment by MateuszBogdan** [comment]
I am having same problem. I have checked all log tabs, nothing interesting happens. It might be correlated to VS Code 1.49.0 update.

I am using the same versions as noted by @LeHoangDev.

**Comment by dineug** [comment]
Looks like an Electronjs 9.0 bug.
![vscode-vuerd_export-1](https://user-images.githubusercontent.com/45829489/93205772-536b1000-f793-11ea-9339-c8e65788f420.png)

I'm going to change it as below.
![vscode-vuerd_export-2](https://user-images.githubusercontent.com/45829489/93205831-6c73c100-f793-11ea-928d-a7fc646daa5d.png)
