### ISSUE TITLE
The road to vuerd 2

### ISSUE THREAD

**Issue by dineug** [vuerd/vuerd-vscode#102]
## UI Panel Extension Modularization  
If you have more features, your library will become too large and you need to be able to choose.  

### UI Related Issues List  
- [SQL-Query generator](https://github.com/vuerd/vuerd/issues/3)
- [Custom generate code](https://github.com/vuerd/vuerd-vscode/issues/94)  

I've implemented all the features I want, so I'm not motivated at the moment.

I don't know when the v2.0.0 task will start.

Maybe I'll work on it after my new pet project.

Currently, we are only going to do small bugs and maintenance.

If you have a feature you want, open the issue.

**Comment by dineug** [comment]
## TODO

- [x] [Integrating with reactive system components](https://github.com/vuerd/vuerd/issues/181)
- [x] [Extension Panel API](https://github.com/vuerd/vuerd/issues/182)
- [x] [Zoom Level Support](https://github.com/vuerd/vuerd/issues/183)

**Comment by nikkoa** [comment]
Thanks for the awesome extension! Any chance #8 can be included? The fixed notation on the other side of the relationship can get misleading.
