### ISSUE TITLE
Window Size does not increase

### ISSUE THREAD

**Issue by fbdtw** [vuerd/vuerd-vscode#109]
Hi Everyone,

thank you for this great tool. Unfortunately, I have the problem that my editor window gets too small very quickly and new entities/tables align themselves in the inner area and thus overlay other tables. How can I change this?

Thank you

Tobias

**Comment by dineug** [comment]
I don't know if you're talking about this,
Canvas size is 2000 by default.
You can change it.

<img width="616" alt="스크린샷 2021-01-26 오후 7 40 27" src="https://user-images.githubusercontent.com/45829489/105834938-7c879100-600e-11eb-87af-42708dddb186.png">

**Comment by fbdtw** [comment]
Thank you so much. That helped. I did not see this as the text color was the same as the background:

![image](https://user-images.githubusercontent.com/69795928/105835288-e7fc3f00-5fcb-11eb-921a-a9fabe8f58bf.png)

But this was, what I was looking for 1-2 hours in the last couple of days, thank you!
