### ISSUE TITLE
best ERD editor I've seen yet

### ISSUE THREAD

**Issue by RandomFractals** [vuerd/vuerd-vscode#2]
not an issue. Just wanted to let you know that I shared your excellent ERD Editor on twitter and in unofficial vscode ext's dev slack ...

https://twitter.com/TarasNovak/status/1224348231087333378

Let me know if you'd like to integrate some bits of it with the Data Preview ext. in code ...

**Comment by dineug** [comment]
Thank you a lot!
It's a big boost to the motivation for development.

**Comment by RandomFractals** [comment]
Your ext. is a gem & really well constructed. 

I took it for a spin the other day and looked at your ext. code briefly.

It's impressive what you are trying to do with it & I hope more devs will recognize the value of such tool as it gets tracking in marketplace.

As someone coming from data modeling background I find tools like this essential for creating data stores and generating code for data access.

I think you got a winner on your hands! :)
