### ISSUE TITLE
Foreign Key Type Mirrors Primary Key Type

### ISSUE THREAD

**Issue by cglusky** [vuerd/vuerd-vscode#24]
When creating tables using Postgresql DB the primary key type and foreign key types are mirrored.  So if you select serial for primary key you get serial for foreign key when it should likely be integer for foreign key type.  When you try to change foreign key it forces a change in primary key.

Have not tried other DB types.

**Comment by dineug** [comment]
Thank you for telling me the missed use case!

I'll add that feature as an option so you can control it.
