### ISSUE TITLE
[bug] Moving tables on HiDPI screens

### ISSUE THREAD

**Issue by kubawolanin** [vuerd/vuerd-vscode#3]
Hi. Really nice extension!

When I was playing around with it [on the demo site](https://vuerd.github.io/vuerd-docs/iframe.html?id=demo-live--vuerd) I observed that dragging and moving tables around on a HiDPI screen causes an offset.
This does not occur on screens with standard pixel ratio.

See attached gif demonstrating the issue:
![hidpi](https://user-images.githubusercontent.com/2270505/74313579-3e994a80-4d74-11ea-9081-bf4204fc756f.gif)

I'm using latest Edge (Chromium-based) on Windows 10.

Cheers

**Comment by dineug** [comment]
Thank you for the very kind issue.
I could easily recognize it.
