### ISSUE TITLE
Can I edit the JSON?

### ISSUE THREAD

**Issue by retorquere** [vuerd/vuerd-vscode#5]
I'd sometimes prefer to make quick changes by just hand-editign the JSON. I can edit the JSON in the editor but the changes don't seem to "stick".

**Comment by dineug** [comment]
Editor is highly vulnerable to bugs due to json data dependency
I don't recommend it.

If you do, you will need to save the modification and reload the editor webview.

**Comment by retorquere** [comment]
Alright, thanks. Shame though, this was my primary use-case.
