### ISSUE TITLE
Unable to install Extension 'dineug.vuerd-vscode-0.6.1' as it is not compatible with Code '1.24.0'.

### ISSUE THREAD

**Issue by lidaguang1989** [vuerd/vuerd-vscode#52]
when I install it in VSCode 1.24.0, I got following error:

Unable to install Extension 'dineug.vuerd-vscode-0.6.1' as it is not compatible with Code '1.24.0'.

**Comment by dineug** [comment]
vscode support >= v1.46.x
Update vscode and try again

**Comment by lidaguang1989** [comment]
> vscode support >= v1.46.x
> Update vscode and try again

It works now, thanks,.
