### ISSUE TITLE
PostgreSQL database type causes lockup in dataType column

### ISSUE THREAD

**Issue by seamusm02** [vuerd/vuerd-vscode#6]
With PostgreSQL selected, typing in the dataType column causes a lockup after the initial lookup.  All other db types seem to work fine!  Thanks for this nice extension!

![postgres_issue](https://user-images.githubusercontent.com/59479271/78937945-f0a07a80-7a76-11ea-8dd9-8e9b943f36f6.gif)

**Comment by dineug** [comment]
Thanks for letting me know!

**Comment by seamusm02** [comment]
I forgot to mention this issue was happening on v0.4.2
