### ISSUE TITLE
Crow's foot notation: Zero or One

### ISSUE THREAD

**Issue by simeonlin** [vuerd/vuerd-vscode#8]
I think there should be an improvement on the crow foot notation on the relationships.
From Wikipedia: (https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#Crow's_foot_notation)

> Three symbols are used to represent cardinality:
> -the ring represents "zero"
> -the dash represents "one"
> -the crow's foot represents "many" or "infinite"
> These symbols are used in pairs to represent the four types of cardinality that an entity may have in a relationship. The inner component of the notation represents the minimum, and the outer component represents the maximum.
> 
> ring and dash → minimum zero, maximum one (optional)
> **dash and dash → minimum one, maximum one (mandatory)**
> **ring and crow's foot → minimum zero, maximum many (optional)**
> dash and crow's foot → minimum one, maximum many (mandatory)

Issues:

- At the moment to-many-relationships are marked with three symbols ring, dash and crow's foot instead of only ring and crow's foot.

- And if I mark a foreign-key-column in the List-view as mandatory the symbol stays at 'ring and dash' instead of 'dash' or 'dash and dash'.

(Just found this VS Code-Extension and I'm amazed!) 🥇

**Comment by dineug** [comment]
(ZeroOne, ZeroN, OneN, OneOnly, N)
Now I know!

But I don't think it's going to be possible for me to revise it now.

I'm preparing for major version 1.0.
The current version only planned to fix important bugs.

Instead, I will reflect the notation you told me in 1.0!

Thanks for letting me know!

**Comment by simeonlin** [comment]
Ok, thank you that's fine! 👍 

Do you already have a time horizon for 1.0? 
Just: Is it about weeks or months? :)
I'm considering using your great tool in my database-courses I'm teaching.

**Comment by dineug** [comment]
I'm thinking maybe it'll be completed between June and July.
