### ISSUE TITLE
index suppoort

### ISSUE THREAD

**Issue by mikemeerschaert** [vuerd/vuerd-vscode#9]
is the generation of database indexes supported?

**Comment by dineug** [comment]
Not currently supported

I think it will be added around v1.1.0 for future plans.

**Comment by Kaihusrav** [comment]
in ERD mode, the tables appearance is bog enough. Sometimes more compact view is required. somthing like hiding extra attributes and resizing tablewould be fantastic good. And full edditing (adding tables, columns) in tabular\Grid mode would be also greate.

**Comment by dineug** [comment]
Table Properties view is currently supported
![image](https://user-images.githubusercontent.com/45829489/89310022-2533e400-d6af-11ea-8c30-146f6b785fef.png)

The function to delete additional tables and columns on the grid
I'll take a positive look at it.
